apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server-{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local
      access: proxy
      isDefault: true
    - name: Loki
      type: loki
      url: http://loki-{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local
      access: proxy
