// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game.proto

package game

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Move_Direction int32

const (
	Move_NONE       Move_Direction = 0
	Move_UP         Move_Direction = 1
	Move_DOWN       Move_Direction = 2
	Move_LEFT       Move_Direction = 3
	Move_UP_LEFT    Move_Direction = 4
	Move_DOWN_LEFT  Move_Direction = 5
	Move_RIGHT      Move_Direction = 6
	Move_UP_RIGHT   Move_Direction = 7
	Move_DOWN_RIGHT Move_Direction = 8
)

var Move_Direction_name = map[int32]string{
	0: "NONE",
	1: "UP",
	2: "DOWN",
	3: "LEFT",
	4: "UP_LEFT",
	5: "DOWN_LEFT",
	6: "RIGHT",
	7: "UP_RIGHT",
	8: "DOWN_RIGHT",
}

var Move_Direction_value = map[string]int32{
	"NONE":       0,
	"UP":         1,
	"DOWN":       2,
	"LEFT":       3,
	"UP_LEFT":    4,
	"DOWN_LEFT":  5,
	"RIGHT":      6,
	"UP_RIGHT":   7,
	"DOWN_RIGHT": 8,
}

func (x Move_Direction) String() string {
	return proto.EnumName(Move_Direction_name, int32(x))
}

func (Move_Direction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{2, 0}
}

// Gameboard representation
type GameBoard struct {
	Players              map[int32]*Player `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Id                   int32             `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Rad                  float64           `protobuf:"fixed64,3,opt,name=rad,proto3" json:"rad,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GameBoard) Reset()         { *m = GameBoard{} }
func (m *GameBoard) String() string { return proto.CompactTextString(m) }
func (*GameBoard) ProtoMessage()    {}
func (*GameBoard) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{0}
}

func (m *GameBoard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameBoard.Unmarshal(m, b)
}
func (m *GameBoard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameBoard.Marshal(b, m, deterministic)
}
func (m *GameBoard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameBoard.Merge(m, src)
}
func (m *GameBoard) XXX_Size() int {
	return xxx_messageInfo_GameBoard.Size(m)
}
func (m *GameBoard) XXX_DiscardUnknown() {
	xxx_messageInfo_GameBoard.DiscardUnknown(m)
}

var xxx_messageInfo_GameBoard proto.InternalMessageInfo

func (m *GameBoard) GetPlayers() map[int32]*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *GameBoard) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GameBoard) GetRad() float64 {
	if m != nil {
		return m.Rad
	}
	return 0
}

type Player struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	X                    float64  `protobuf:"fixed64,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,3,opt,name=y,proto3" json:"y,omitempty"`
	Rad                  float64  `protobuf:"fixed64,4,opt,name=rad,proto3" json:"rad,omitempty"`
	Ringrad              float64  `protobuf:"fixed64,5,opt,name=ringrad,proto3" json:"ringrad,omitempty"`
	Color                int32    `protobuf:"varint,6,opt,name=color,proto3" json:"color,omitempty"`
	Kills                int32    `protobuf:"varint,7,opt,name=kills,proto3" json:"kills,omitempty"`
	RingEnabled          bool     `protobuf:"varint,8,opt,name=ringEnabled,proto3" json:"ringEnabled,omitempty"`
	Speed                int32    `protobuf:"varint,9,opt,name=speed,proto3" json:"speed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{1}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Player) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Player) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Player) GetRad() float64 {
	if m != nil {
		return m.Rad
	}
	return 0
}

func (m *Player) GetRingrad() float64 {
	if m != nil {
		return m.Ringrad
	}
	return 0
}

func (m *Player) GetColor() int32 {
	if m != nil {
		return m.Color
	}
	return 0
}

func (m *Player) GetKills() int32 {
	if m != nil {
		return m.Kills
	}
	return 0
}

func (m *Player) GetRingEnabled() bool {
	if m != nil {
		return m.RingEnabled
	}
	return false
}

func (m *Player) GetSpeed() int32 {
	if m != nil {
		return m.Speed
	}
	return 0
}

// Direction to move
type Move struct {
	Userkey              int32          `protobuf:"varint,1,opt,name=userkey,proto3" json:"userkey,omitempty"`
	Gameid               int32          `protobuf:"varint,2,opt,name=gameid,proto3" json:"gameid,omitempty"`
	Direction            Move_Direction `protobuf:"varint,3,opt,name=direction,proto3,enum=game.Move_Direction" json:"direction,omitempty"`
	EnableRing           bool           `protobuf:"varint,4,opt,name=enableRing,proto3" json:"enableRing,omitempty"`
	HitPlayers           []int32        `protobuf:"varint,5,rep,packed,name=hitPlayers,proto3" json:"hitPlayers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Move) Reset()         { *m = Move{} }
func (m *Move) String() string { return proto.CompactTextString(m) }
func (*Move) ProtoMessage()    {}
func (*Move) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{2}
}

func (m *Move) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Move.Unmarshal(m, b)
}
func (m *Move) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Move.Marshal(b, m, deterministic)
}
func (m *Move) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Move.Merge(m, src)
}
func (m *Move) XXX_Size() int {
	return xxx_messageInfo_Move.Size(m)
}
func (m *Move) XXX_DiscardUnknown() {
	xxx_messageInfo_Move.DiscardUnknown(m)
}

var xxx_messageInfo_Move proto.InternalMessageInfo

func (m *Move) GetUserkey() int32 {
	if m != nil {
		return m.Userkey
	}
	return 0
}

func (m *Move) GetGameid() int32 {
	if m != nil {
		return m.Gameid
	}
	return 0
}

func (m *Move) GetDirection() Move_Direction {
	if m != nil {
		return m.Direction
	}
	return Move_NONE
}

func (m *Move) GetEnableRing() bool {
	if m != nil {
		return m.EnableRing
	}
	return false
}

func (m *Move) GetHitPlayers() []int32 {
	if m != nil {
		return m.HitPlayers
	}
	return nil
}

func init() {
	proto.RegisterEnum("game.Move_Direction", Move_Direction_name, Move_Direction_value)
	proto.RegisterType((*GameBoard)(nil), "game.GameBoard")
	proto.RegisterMapType((map[int32]*Player)(nil), "game.GameBoard.PlayersEntry")
	proto.RegisterType((*Player)(nil), "game.Player")
	proto.RegisterType((*Move)(nil), "game.Move")
}

func init() {
	proto.RegisterFile("game.proto", fileDescriptor_38fc58335341d769)
}

var fileDescriptor_38fc58335341d769 = []byte{
	// 465 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x52, 0x4d, 0x6b, 0xdb, 0x40,
	0x10, 0xcd, 0xea, 0x5b, 0x23, 0xd7, 0x11, 0x4b, 0x28, 0x4b, 0x28, 0x45, 0xe8, 0xa4, 0x93, 0x5a,
	0xd4, 0x52, 0x4a, 0x8f, 0x69, 0xdc, 0xa4, 0xd0, 0x3a, 0x66, 0x13, 0x53, 0xe8, 0x25, 0xc8, 0xd6,
	0xe2, 0x8a, 0xc8, 0x92, 0x59, 0x2b, 0xc6, 0xfa, 0x3f, 0xbd, 0xf7, 0x4f, 0xf4, 0x87, 0x95, 0xd9,
	0xb5, 0x64, 0xd3, 0xdb, 0xbc, 0x37, 0xef, 0xcd, 0xcc, 0xce, 0x0e, 0xc0, 0x2a, 0x5f, 0x8b, 0x74,
	0x23, 0x9b, 0xb6, 0xa1, 0x16, 0xc6, 0xf1, 0x1f, 0x02, 0xfe, 0x4d, 0xbe, 0x16, 0x57, 0x4d, 0x2e,
	0x0b, 0xfa, 0x01, 0xdc, 0x4d, 0x95, 0x77, 0x42, 0x6e, 0x19, 0x89, 0xcc, 0x24, 0xc8, 0x5e, 0xa5,
	0xca, 0x31, 0x28, 0xd2, 0x99, 0x4e, 0x4f, 0xea, 0x56, 0x76, 0xbc, 0x17, 0xd3, 0x31, 0x18, 0x65,
	0xc1, 0x8c, 0x88, 0x24, 0x36, 0x37, 0xca, 0x82, 0x86, 0x60, 0xca, 0xbc, 0x60, 0x66, 0x44, 0x12,
	0xc2, 0x31, 0xbc, 0xbc, 0x85, 0xd1, 0xa9, 0x15, 0x15, 0x4f, 0xa2, 0x63, 0x44, 0x59, 0x30, 0xa4,
	0x31, 0xd8, 0xbb, 0xbc, 0x7a, 0x16, 0xaa, 0x4c, 0x90, 0x8d, 0x74, 0x67, 0x6d, 0xe2, 0x3a, 0xf5,
	0xc9, 0xf8, 0x48, 0xe2, 0xbf, 0x04, 0x1c, 0xcd, 0x1e, 0xda, 0x92, 0xa1, 0xed, 0x08, 0xc8, 0x5e,
	0xd9, 0x09, 0x27, 0x7b, 0x44, 0xdd, 0x61, 0x04, 0xd2, 0xf5, 0x23, 0x59, 0xc3, 0x48, 0x94, 0x81,
	0x2b, 0xcb, 0x7a, 0x85, 0xac, 0xad, 0xd8, 0x1e, 0xd2, 0x0b, 0xb0, 0x97, 0x4d, 0xd5, 0x48, 0xe6,
	0xa8, 0xd2, 0x1a, 0x20, 0xfb, 0x54, 0x56, 0xd5, 0x96, 0xb9, 0x9a, 0x55, 0x80, 0x46, 0x10, 0xa0,
	0x6d, 0x52, 0xe7, 0x8b, 0x4a, 0x14, 0xcc, 0x8b, 0x48, 0xe2, 0xf1, 0x53, 0x0a, 0x7d, 0xdb, 0x8d,
	0x10, 0x05, 0xf3, 0xb5, 0x4f, 0x81, 0xf8, 0xb7, 0x01, 0xd6, 0xf7, 0x66, 0x27, 0x70, 0x8c, 0xe7,
	0xad, 0x90, 0xc7, 0x6d, 0xf4, 0x90, 0xbe, 0x04, 0x07, 0x77, 0x30, 0x6c, 0xf6, 0x80, 0x68, 0x06,
	0x7e, 0x51, 0x4a, 0xb1, 0x6c, 0xcb, 0xa6, 0x56, 0x0f, 0x1c, 0x67, 0x17, 0x7a, 0x5b, 0x58, 0x30,
	0xbd, 0xee, 0x73, 0xfc, 0x28, 0xa3, 0xaf, 0x01, 0x84, 0x9a, 0x87, 0x97, 0xf5, 0x4a, 0x6d, 0xc1,
	0xe3, 0x27, 0x0c, 0xe6, 0x7f, 0x95, 0xed, 0xe1, 0x8b, 0x98, 0x1d, 0x99, 0x89, 0xcd, 0x4f, 0x98,
	0x78, 0x07, 0xfe, 0x50, 0x97, 0x7a, 0x60, 0x4d, 0xef, 0xa6, 0x93, 0xf0, 0x8c, 0x3a, 0x60, 0xcc,
	0x67, 0x21, 0x41, 0xe6, 0xfa, 0xee, 0xc7, 0x34, 0x34, 0x30, 0xfa, 0x36, 0xf9, 0xf2, 0x10, 0x9a,
	0x34, 0x00, 0x77, 0x3e, 0x7b, 0x54, 0xc0, 0xa2, 0x2f, 0xc0, 0x47, 0x81, 0x86, 0x36, 0xf5, 0xc1,
	0xe6, 0x5f, 0x6f, 0x6e, 0x1f, 0x42, 0x87, 0x8e, 0xc0, 0x9b, 0xcf, 0x1e, 0x35, 0x72, 0xe9, 0x18,
	0x40, 0xe9, 0x34, 0xf6, 0xb2, 0xcf, 0x10, 0xe0, 0xf1, 0xdd, 0x0b, 0xb9, 0x2b, 0x97, 0x82, 0xbe,
	0x87, 0xf3, 0xfb, 0x56, 0x8a, 0x7c, 0x8d, 0xe4, 0x42, 0xdd, 0x2c, 0x1c, 0x9f, 0x7e, 0x79, 0xfe,
	0xdf, 0xb9, 0xc6, 0x67, 0x09, 0x79, 0x4b, 0xae, 0xbc, 0x9f, 0x4e, 0xfa, 0x06, 0x33, 0x0b, 0x47,
	0xdd, 0xfe, 0xbb, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x4f, 0x2f, 0xbf, 0x09, 0x03, 0x00,
	0x00,
}
