apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-ip
  namespace: metallb-system
spec:
  ipAddressPools:
  - orbstrike-pool
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: orbstrike-pool
  namespace: metallb-system
spec:
  addresses:
    - 10.1.1.80
