apiVersion: v1
kind: Secret
metadata:
  name: orbstrike-orchestrator-environment
  namespace: orbstrike-system
type: Opaque
stringData:
  port: "443"
  timeoutmin: "180"
  secret: "awe9Kl2ZGEtjnoPoTjCXrnNppw4k6Kq9"
  logfile: "/var/log/orbstrike.orchestrator.log"
  logoptions: "ERROR|WARNING|INFORMATION"
  maxlogsizekb: "500"
  logstdout: "true"
  base64_ssl_certificate: ""
  base64_ssl_privatekey: ""
  base64_ssl_ca: ""
  dbshardnodes: |
    cache-db-set-0.cache-db-svc.orbstrike-system.svc.cluster.local:6379,
    cache-db-set-1.cache-db-svc.orbstrike-system.svc.cluster.local:6379,
    cache-db-set-2.cache-db-svc.orbstrike-system.svc.cluster.local:6379
  dbusername: "u_orbstrike_api_rw"
  dbpassword: "SuperSecret123"
  db_base64_ssl_certificate: |
    base64cert
  db_base64_ssl_privatekey: |
    base64key
  db_base64_ssl_ca: |
    base64cert
  gameserver_base64_ssl_ca: ""
  focontrollerdowntimethresholdms: "3000"
  failoverintervalms: "1000"
  gamelifetimemin: "180"
  gamejointimeoutsec: "10"
  dailyusergamelimit: "20"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator-deployment
  namespace: orbstrike-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
        - name: orchestrator
          image: megakuul/orbstrike-orchestrator:latest
          envFrom:
          - secretRef:
              name: orbstrike-orchestrator-environment
          ports:
          - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator-lb
  namespace: orbstrike-system
spec:
  type: LoadBalancer
  selector:
    app: orchestrator
  ports:
    - protocol: TCP
      port: 433
      targetPort: 443
