apiVersion: v1
kind: Secret
metadata:
  name: orbstrike-server-environment
  namespace: orbstrike-system
type: Opaque
stringData:
  port: 10187
  addr: ""
  secret: "awe9Kl2ZGEtjnoPoTjCXrnNppw4k6Kq9"
  logfile: "/var/log/orbstrike.orchestrator.log"
  logoptions: "ERROR|WARNING|INFORMATION"
  maxlogsizekb: "500"
  logstdout: "true"
  base64_ssl_certificate: ""
  base64_ssl_privatekey: ""
  base64_ssl_ca: ""
  dbshardnodes: |
    cache-db-set-0.cache-db-svc.orbstrike-system.svc.cluster.local:6379,
    cache-db-set-1.cache-db-svc.orbstrike-system.svc.cluster.local:6379,
    cache-db-set-2.cache-db-svc.orbstrike-system.svc.cluster.local:6379
  dbusername: "u_orbstrike_api_rw"
  dbpassword: "SuperSecret123"
  db_base64_ssl_certificate: |
    base64cert
  db_base64_ssl_privatekey: |
    base64key
  db_base64_ssl_ca:  |
    base64cert
  maxchannelsize: "10"
  requestperworker: "15"
  syncintervalms: "1000"
  downtimethresholdms: "5000"
  gameovermessage: "Game Over|Garbage Collected"
---
apiVersion: v1
kind: Service
metadata:
  name: server-svc
  namespace: orbstrike-system
spec:
  clusterIP: none
  selector: server-cluster
  ports:
    - protocol: TCP
      port: 10187
      targetPort: 10187
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: server-deployment
  namespace: orbstrike-system
spec:
  serviceName: "server-svc"
  replicas: 3
  selector:
    matchLabels:
      app: server-cluster
  template:
    metadata:
      labels:
        app: server-cluster
    spec:
      containers:
        - name: server-container
          image: megakuul/orbstrike-server:latest
          envFrom:
          - secretRef:
              name: orbstrike-server-environment
          ports:
          - containerPort: 10187
