{{- if not .Values.orchestratorSpeakerIP }}
{{- fail "Value orchestratorSpeakerIP is required!" }}
{{- end }}
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-ip
  namespace: {{ .Release.Namespace }}
spec:
  ipAddressPools:
  - ip-pool-{{ .Release.Name }}
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-pool-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  addresses:
    - {{ .Values.orchestratorSpeakerIP }}
