apiVersion: v1
kind: Service
metadata:
  name: server-svc-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: none
  selector: server-cluster
  ports:
    - protocol: TCP
      port: {{ .Values.serverPort }}
      targetPort: {{ .Values.serverPort }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: server-deployment
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: "server-svc-{{ .Release.Name }}"
  replicas: {{ .Values.serverReplicas }}
  selector:
    matchLabels:
      app: server-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: server-{{ .Release.Name }}
    spec:
      containers:
        - name: server-{{ .Release.Name }}
          image: megakuul/orbstrike-server:latest
          envFrom:
          - secretRef:
              name: server-env-{{ .Release.Name }}
          ports:
          - containerPort: {{ .Values.serverPort }}
          resources:
            {{- toYaml .Values.serverResources | nindent 10 }}
