{{- if not .Values.orchestratorSpeakerIP }}
{{- fail "Value orchestratorSpeakerIP is required!" }}
{{- end }}
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-ip-{{ .Release.Namespace }}-{{ .Release.Name }}
  namespace: {{ .Values.metallbNamespace }}
spec:
  ipAddressPools:
  - ip-pool-{{ .Release.Name }}
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-pool-{{ .Release.Namespace }}-{{ .Release.Name }}
  namespace: {{ .Values.metallbNamespace }}
spec:
  addresses:
    - {{ .Values.orchestratorSpeakerIP }}
