apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.serverDefaultReplicas }}
  selector:
    matchLabels:
      app: server-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: server-{{ .Release.Name }}
    spec:
      containers:
        - name: server-{{ .Release.Name }}
          image: megakuul/orbstrike-server:latest
          imagePullPolicy: Always
          envFrom:
          - secretRef:
              name: server-env-{{ .Release.Name }}
          ports:
          - containerPort: {{ .Values.serverPort }}
          resources:
            {{- toYaml .Values.serverResources | nindent 12 }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: server-hpa-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: server-deployment-{{ .Release.Name }}
  minReplicas: {{ .Values.serverMinReplicas }}
  maxReplicas: {{ .Values.serverMaxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.serverScaleUtil }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.serverScaleUtil }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
---
apiVersion: v1
kind: Service
metadata:
  name: server-svc-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  selector:
    app: server-{{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.serverPort }}
      targetPort: {{ .Values.serverPort }}
