// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Move_Direction int32

const (
	Move_UP         Move_Direction = 0
	Move_DOWN       Move_Direction = 1
	Move_LEFT       Move_Direction = 2
	Move_RIGHT      Move_Direction = 3
	Move_UP_LEFT    Move_Direction = 4
	Move_UP_RIGHT   Move_Direction = 5
	Move_DOWN_LEFT  Move_Direction = 6
	Move_DOWN_RIGHT Move_Direction = 7
)

var Move_Direction_name = map[int32]string{
	0: "UP",
	1: "DOWN",
	2: "LEFT",
	3: "RIGHT",
	4: "UP_LEFT",
	5: "UP_RIGHT",
	6: "DOWN_LEFT",
	7: "DOWN_RIGHT",
}

var Move_Direction_value = map[string]int32{
	"UP":         0,
	"DOWN":       1,
	"LEFT":       2,
	"RIGHT":      3,
	"UP_LEFT":    4,
	"UP_RIGHT":   5,
	"DOWN_LEFT":  6,
	"DOWN_RIGHT": 7,
}

func (x Move_Direction) String() string {
	return proto.EnumName(Move_Direction_name, int32(x))
}

func (Move_Direction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{2, 0}
}

// Gameboard representation
type GameBoard struct {
	Players              []*Player `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GameBoard) Reset()         { *m = GameBoard{} }
func (m *GameBoard) String() string { return proto.CompactTextString(m) }
func (*GameBoard) ProtoMessage()    {}
func (*GameBoard) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{0}
}

func (m *GameBoard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameBoard.Unmarshal(m, b)
}
func (m *GameBoard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameBoard.Marshal(b, m, deterministic)
}
func (m *GameBoard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameBoard.Merge(m, src)
}
func (m *GameBoard) XXX_Size() int {
	return xxx_messageInfo_GameBoard.Size(m)
}
func (m *GameBoard) XXX_DiscardUnknown() {
	xxx_messageInfo_GameBoard.DiscardUnknown(m)
}

var xxx_messageInfo_GameBoard proto.InternalMessageInfo

func (m *GameBoard) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

type Player struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Color                int32    `protobuf:"varint,3,opt,name=color,proto3" json:"color,omitempty"`
	Kills                int32    `protobuf:"varint,4,opt,name=kills,proto3" json:"kills,omitempty"`
	RingEnabled          bool     `protobuf:"varint,5,opt,name=ringEnabled,proto3" json:"ringEnabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{1}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Player) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Player) GetColor() int32 {
	if m != nil {
		return m.Color
	}
	return 0
}

func (m *Player) GetKills() int32 {
	if m != nil {
		return m.Kills
	}
	return 0
}

func (m *Player) GetRingEnabled() bool {
	if m != nil {
		return m.RingEnabled
	}
	return false
}

// Direction to move
type Move struct {
	Direction            Move_Direction `protobuf:"varint,1,opt,name=direction,proto3,enum=game.Move_Direction" json:"direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Move) Reset()         { *m = Move{} }
func (m *Move) String() string { return proto.CompactTextString(m) }
func (*Move) ProtoMessage()    {}
func (*Move) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{2}
}

func (m *Move) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Move.Unmarshal(m, b)
}
func (m *Move) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Move.Marshal(b, m, deterministic)
}
func (m *Move) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Move.Merge(m, src)
}
func (m *Move) XXX_Size() int {
	return xxx_messageInfo_Move.Size(m)
}
func (m *Move) XXX_DiscardUnknown() {
	xxx_messageInfo_Move.DiscardUnknown(m)
}

var xxx_messageInfo_Move proto.InternalMessageInfo

func (m *Move) GetDirection() Move_Direction {
	if m != nil {
		return m.Direction
	}
	return Move_UP
}

func init() {
	proto.RegisterEnum("game.Move_Direction", Move_Direction_name, Move_Direction_value)
	proto.RegisterType((*GameBoard)(nil), "game.GameBoard")
	proto.RegisterType((*Player)(nil), "game.Player")
	proto.RegisterType((*Move)(nil), "game.Move")
}

func init() {
	proto.RegisterFile("game.proto", fileDescriptor_38fc58335341d769)
}

var fileDescriptor_38fc58335341d769 = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0x4d, 0x6b, 0xf2, 0x40,
	0x10, 0xc7, 0x9f, 0xd5, 0x24, 0x9a, 0x89, 0x8f, 0x0d, 0x83, 0x87, 0xd0, 0x53, 0x48, 0x69, 0xb1,
	0x97, 0x08, 0xf1, 0xd2, 0xb3, 0x68, 0x6d, 0xa1, 0x2f, 0x21, 0x35, 0x14, 0x7a, 0x91, 0xbc, 0x2c,
	0x69, 0x30, 0x71, 0x65, 0x8d, 0xa2, 0xdf, 0xa8, 0x1f, 0xb3, 0xec, 0x2e, 0x6a, 0x4f, 0x3b, 0xff,
	0xdf, 0x6f, 0x87, 0x1d, 0x76, 0x00, 0x8a, 0xa4, 0xa6, 0xfe, 0x86, 0xb3, 0x86, 0xa1, 0x26, 0x6a,
	0x6f, 0x0c, 0xe6, 0x3c, 0xa9, 0xe9, 0x84, 0x25, 0x3c, 0xc7, 0x3b, 0xe8, 0x6c, 0xaa, 0xe4, 0x48,
	0xf9, 0xd6, 0x21, 0x6e, 0x7b, 0x68, 0x05, 0x3d, 0x5f, 0x36, 0x84, 0x12, 0x46, 0x27, 0xe9, 0x71,
	0x30, 0x14, 0xc2, 0x1e, 0x90, 0x83, 0x43, 0x5c, 0x32, 0xd4, 0x23, 0x72, 0x10, 0xe9, 0xe8, 0xb4,
	0x54, 0x3a, 0xe2, 0x00, 0xf4, 0x8c, 0x55, 0x8c, 0x3b, 0x6d, 0x49, 0x54, 0x10, 0x74, 0x55, 0x56,
	0xd5, 0xd6, 0xd1, 0x14, 0x95, 0x01, 0x5d, 0xb0, 0x78, 0xb9, 0x2e, 0x66, 0xeb, 0x24, 0xad, 0x68,
	0xee, 0xe8, 0x2e, 0x19, 0x76, 0xa3, 0xbf, 0xc8, 0xfb, 0x21, 0xa0, 0xbd, 0xb2, 0x3d, 0xc5, 0x00,
	0xcc, 0xbc, 0xe4, 0x34, 0x6b, 0x4a, 0xb6, 0x96, 0x4f, 0xf7, 0x83, 0x81, 0x1a, 0x53, 0x68, 0x7f,
	0x7a, 0x72, 0xd1, 0xe5, 0x9a, 0x57, 0x81, 0x79, 0xe6, 0x68, 0x40, 0x2b, 0x0e, 0xed, 0x7f, 0xd8,
	0x05, 0x6d, 0xfa, 0xfe, 0xf9, 0x66, 0x13, 0x51, 0xbd, 0xcc, 0x1e, 0x17, 0x76, 0x0b, 0x4d, 0xd0,
	0xa3, 0xe7, 0xf9, 0xd3, 0xc2, 0x6e, 0xa3, 0x05, 0x9d, 0x38, 0x5c, 0x4a, 0xae, 0x61, 0x0f, 0xba,
	0x71, 0xb8, 0x54, 0x4a, 0xc7, 0xff, 0x60, 0x8a, 0x4e, 0x25, 0x0d, 0xec, 0x03, 0xc8, 0xa8, 0x74,
	0x27, 0x78, 0x00, 0x4b, 0xfc, 0xe9, 0x07, 0xe5, 0xfb, 0x32, 0xa3, 0x78, 0x0f, 0x20, 0x62, 0xbc,
	0xc9, 0x93, 0x86, 0x22, 0x5c, 0x66, 0xbd, 0xbe, 0x52, 0xf5, 0x79, 0x01, 0x93, 0xdb, 0xaf, 0x9b,
	0xa2, 0x6c, 0xbe, 0x77, 0xa9, 0x9f, 0xb1, 0x7a, 0x54, 0xd3, 0x22, 0x59, 0xed, 0x76, 0xd5, 0x88,
	0xf1, 0x74, 0xdb, 0xf0, 0x72, 0x45, 0x47, 0x72, 0x75, 0xa9, 0x21, 0x8f, 0xf1, 0x6f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xa3, 0x5f, 0x04, 0x89, 0xcf, 0x01, 0x00, 0x00,
}
